version: '3.8'
services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - realo-network
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    container_name: admin
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:${DISCOVERY_SERVER_PORT}/eureka
      - DB_CONNECTION_URI=${DB_CONNECTION_URI}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVER_PORT=${ADMIN_SERVICE_SERVER_PORT}
    depends_on:
      - discovery
      - mysql
    networks:
      - realo-network

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: api
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:${DISCOVERY_SERVER_PORT}/eureka
      - SERVER_PORT=${API_SERVICE_SERVER_PORT}
      - ADMIN-SERVICE=admin-service
    depends_on:
      - discovery
      - admin-service
    networks:
      - realo-network

  discovery:
    build:
      context: ./discovery
      dockerfile: Dockerfile
    container_name: discovery
    environment:
      - DISCOVERY_SERVER_PORT=${DISCOVERY_SERVER_PORT}
    networks:
      - realo-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:${DISCOVERY_SERVER_PORT}/eureka
      - UI_URI=http://ui:80
      - GATEWAY_SERVER_PORT=${GATEWAY_SERVER_PORT}
    depends_on:
      - discovery
      - ui
    networks:
      - realo-network

  ui:
    build:
      context: ./ui
      args:
        REACT_APP_API_URL: http://localhost:${GATEWAY_SERVER_PORT}
      dockerfile: Dockerfile
    container_name: ui
    networks:
      - realo-network

volumes:
  mysql_data:

networks:
  realo-network:
    driver: bridge